# Generated by Django 4.2.2 on 2025-04-13 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cannabis_db', '0001_initial'),
        ('addresses', '0001_initial'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='saves',
            field=models.ManyToManyField(blank=True, null=True, related_name='strain_saves', to='memberships.profile'),
        ),
        migrations.AddField(
            model_name='strain',
            name='seeds',
            field=models.ManyToManyField(blank=True, null=True, related_name='seed_bank_brands', to='cannabis_db.brand'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_details_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.straindetailslist'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_lineage_details_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.strainlineagedetailslist'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_metas_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strain_metas', to='cannabis_db.metasset'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.strainspecificationssets'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.straintype'),
        ),
        migrations.AddField(
            model_name='strain',
            name='terpene_profile',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.terpeneprofile'),
        ),
        migrations.AddField(
            model_name='strain',
            name='terpenes_reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.terpenedetailsset'),
        ),
        migrations.AddField(
            model_name='strain',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strain',
            name='users_smoked',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_smoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strain',
            name='vendors',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='dispensaries',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.dispensary'),
        ),
        migrations.AddField(
            model_name='metasset',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metasset',
            name='meta_keywords',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.keywordsset'),
        ),
        migrations.AddField(
            model_name='keywordsset',
            name='keywords',
            field=models.ManyToManyField(to='cannabis_db.keywords'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='images',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.galleryimagesset'),
        ),
        migrations.AddField(
            model_name='helpswithreportlistset',
            name='helps_with_report_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.helpswithreportlist'),
        ),
        migrations.AddField(
            model_name='helpswithreportlist',
            name='helps_with_report_list',
            field=models.ManyToManyField(to='cannabis_db.helpswithreport'),
        ),
        migrations.AddField(
            model_name='galleryimagesset',
            name='images',
            field=models.ManyToManyField(blank=True, max_length=500, null=True, to='cannabis_db.galleryimage'),
        ),
        migrations.AddField(
            model_name='flavorsdetailslistset',
            name='flavors_list_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.flavorsdetailslist'),
        ),
        migrations.AddField(
            model_name='flavorsdetailslist',
            name='flavors_list',
            field=models.ManyToManyField(to='cannabis_db.flavorsdetails'),
        ),
        migrations.AddField(
            model_name='feelingreportlistset',
            name='feeling_report_list_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.feelingreportlist'),
        ),
        migrations.AddField(
            model_name='feelingreportlist',
            name='feeling_report_list',
            field=models.ManyToManyField(to='cannabis_db.feelingreport'),
        ),
        migrations.AddField(
            model_name='effectsreportlistset',
            name='effect_report_list_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.effectreportlist'),
        ),
        migrations.AddField(
            model_name='effectreportlist',
            name='effect_report_list',
            field=models.ManyToManyField(to='cannabis_db.effectreport'),
        ),
        migrations.AddField(
            model_name='dispensarysocialfollowurls',
            name='dispensary_profiles_URLS',
            field=models.ManyToManyField(blank=True, to='cannabis_db.dispensarysocialfollowurl'),
        ),
        migrations.AddField(
            model_name='dispensarysocialfollowurl',
            name='social_profiles_URL_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.dispensarysocialfollowurlicon'),
        ),
        migrations.AddField(
            model_name='dispensarysocialfollows',
            name='social_profiles_URLS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.dispensarysocialfollowurls'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_address',
            field=models.ManyToManyField(blank=True, null=True, to='addresses.address'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_brands',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_brands', to='cannabis_db.brand'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_social_follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.dispensarysocialfollows'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_strains',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_products', to='cannabis_db.strain'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.product'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='saves',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_saves', to='memberships.profile'),
        ),
        migrations.AddField(
            model_name='brandsocialprofile',
            name='social_profiles_URLS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.brandsocialfollowurls'),
        ),
        migrations.AddField(
            model_name='brandsocialfollowurls',
            name='social_profiles_URLS',
            field=models.ManyToManyField(blank=True, to='cannabis_db.brandsocialfollowurl'),
        ),
        migrations.AddField(
            model_name='brand',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_address',
            field=models.ManyToManyField(to='addresses.address'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='strain_brand_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand_strains', to='cannabis_db.strain'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_social_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.brandsocialprofile'),
        ),
        migrations.AddField(
            model_name='brand',
            name='dispensary',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.dispensary'),
        ),
        migrations.AddField(
            model_name='aromaslistset',
            name='aromas_list_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.aromasdetailslist'),
        ),
        migrations.AddField(
            model_name='aromasdetailslist',
            name='aromas_list',
            field=models.ManyToManyField(to='cannabis_db.aromasdetails'),
        ),
    ]
