# Generated by Django 4.2.2 on 2024-03-28 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cannabis_db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='saves',
            field=models.ManyToManyField(blank=True, null=True, related_name='strain_saves', to='memberships.profile'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_details_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.straindetailslist'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_lineage_details_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.strainlineagedetailslist'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_metas_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strain_metas', to='cannabis_db.strainmetas'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.strainspecificationssets'),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.straintype'),
        ),
        migrations.AddField(
            model_name='strain',
            name='terpenes_reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.terpenedetailslistset'),
        ),
        migrations.AddField(
            model_name='strain',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strain',
            name='vendors',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.vendor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='replies',
            field=models.ManyToManyField(to='cannabis_db.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='strain_to_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.strain'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strain_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpswithreportlistset',
            name='helps_with_report_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.helpswithreportlist'),
        ),
        migrations.AddField(
            model_name='helpswithreportlist',
            name='helps_with_report_list',
            field=models.ManyToManyField(to='cannabis_db.helpswithreport'),
        ),
        migrations.AddField(
            model_name='flavorsdetailslistset',
            name='flavors_list_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.flavorsdetailslist'),
        ),
        migrations.AddField(
            model_name='flavorsdetailslist',
            name='flavors_list',
            field=models.ManyToManyField(to='cannabis_db.flavorsdetails'),
        ),
        migrations.AddField(
            model_name='feelingreportlistset',
            name='feeling_report_list_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.feelingreportlist'),
        ),
        migrations.AddField(
            model_name='feelingreportlist',
            name='feeling_report_list',
            field=models.ManyToManyField(to='cannabis_db.feelingreport'),
        ),
        migrations.AddField(
            model_name='dispensarysocialfollowurls',
            name='dispensary_profiles_URLS',
            field=models.ManyToManyField(blank=True, to='cannabis_db.dispensarysocialfollowurl'),
        ),
        migrations.AddField(
            model_name='dispensarysocialfollows',
            name='social_profiles_URLS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.dispensarysocialfollowurls'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_address',
            field=models.ManyToManyField(to='cannabis_db.address'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_brands',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_brands', to='cannabis_db.brand'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_followers',
            field=models.ManyToManyField(related_name='dispensary_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_social_follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.dispensarysocialfollows'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_strains',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_products', to='cannabis_db.strain'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='followers',
            field=models.ManyToManyField(related_name='dispensary_followers', to='memberships.profile'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='saves',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_saves', to='memberships.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(to='cannabis_db.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='strain_to_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.strain'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strain_discussion_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandsocialfollowurls',
            name='social_profiles_URLS',
            field=models.ManyToManyField(blank=True, to='cannabis_db.brandsocialfollowurl'),
        ),
        migrations.AddField(
            model_name='brandsocialfollows',
            name='social_profiles_URLS',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.brandsocialfollowurls'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_followers',
            field=models.ManyToManyField(related_name='strain_brand_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand_strains', to='cannabis_db.strain'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_social_follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.brandsocialfollows'),
        ),
        migrations.AddField(
            model_name='brand',
            name='dispensary',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.dispensary'),
        ),
        migrations.AddField(
            model_name='aromaslistset',
            name='aromas_list_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.aromasdetailslist'),
        ),
        migrations.AddField(
            model_name='aromasdetailslist',
            name='aromas_list',
            field=models.ManyToManyField(to='cannabis_db.aromasdetails'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
