# Generated by Django 4.2.2 on 2024-01-04 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cannabis_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='likes',
            field=models.ManyToManyField(related_name='strain_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('generic', 'Generic'), ('positive', 'Positive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('4', '4'), ('1', '1'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbg', 'CBG '), ('cbd', 'CBD'), ('thc', 'THC')], max_length=1000),
        ),
    ]
