# Generated by Django 4.2.2 on 2024-01-05 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cannabis_db', '0002_strain_likes_alter_feelingreport_type_of_feelings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='strain_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('5', '5'), ('2', '2'), ('1', '1')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='strain_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('indica', 'Indica'), ('hybrid', 'Hybrid'), ('sativa', 'Sativa')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strain',
            name='vendors',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.vendor'),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('indica', 'Indica'), ('hybrid', 'Hybrid'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('indica', 'Indica'), ('hybrid', 'Hybrid'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('thc', 'THC'), ('cbg', 'CBG '), ('cbd', 'CBD')], max_length=1000),
        ),
    ]
