# Generated by Django 4.2.2 on 2025-04-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('catalog', '0001_initial'),
        ('cannabis_db', '0003_brand_brand_metas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_strains',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand_strains', to='cannabis_db.strain'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_address',
            field=models.ManyToManyField(blank=True, null=True, to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand_products', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='accepted_payment_methods',
            field=models.CharField(choices=[('debit_credit', 'Debit/Credit Cards'), ('cash', 'Cash'), ('cash_debit_credit', 'Cash, Debit/Credit Cards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='shopping_options',
            field=models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('pickup_delivery', 'Pickup/Delivery'), ('pickup', 'Pickup')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('seed_bank', 'Seed Bank'), ('medical', 'Medical'), ('medical_recreational', 'Medical & Recreational'), ('recreational', 'Recreational')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='effectreport',
            name='type_of_effects',
            field=models.CharField(choices=[('neutrial', 'Neutrial'), ('positive', 'Positive'), ('negative', 'Negative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('positive', 'Positive'), ('generic', 'Generic'), ('negative', 'Negative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='strain',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_value_label',
            field=models.CharField(blank=True, choices=[('mg', 'mg'), ('percentage', '%')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='title',
            field=models.CharField(blank=True, choices=[('thc', 'THC'), ('cbda', 'CBDA '), ('htcv', 'THCV '), ('cbd', 'CBD'), ('thca', 'THCA '), ('cbg', 'CBG '), ('tac', 'TAC ')], max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
