# Generated by Django 4.2.2 on 2024-01-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0003_vendor_ratings_alter_feelingreport_type_of_feelings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='ratings',
        ),
        migrations.AddField(
            model_name='strain',
            name='ratings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.rating'),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('3', '3'), ('1', '1'), ('4', '4')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbd', 'CBD'), ('cbg', 'CBG '), ('thc', 'THC')], max_length=1000),
        ),
    ]
