# Generated by Django 4.2.2 on 2024-01-13 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cannabis_db', '0003_strain_saves_alter_feelingreport_type_of_feelings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strain',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='dispensary',
            old_name='dispensary_cover_image',
            new_name='dispensary_cover',
        ),
        migrations.RenameField(
            model_name='dispensary',
            old_name='dispensarydescription',
            new_name='dispensary_description',
        ),
        migrations.RenameField(
            model_name='dispensarysocialfollowurls',
            old_name='social_profiles_URLS',
            new_name='dispensary_profiles_URLS',
        ),
        migrations.AddField(
            model_name='strain',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='dispensary_followers',
            field=models.ManyToManyField(related_name='dispensary_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='dispensary_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary', to='cannabis_db.strain'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='dispensary_social_follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.dispensarysocialfollows'),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('4', '4'), ('1', '1'), ('2', '2')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbg', 'CBG '), ('thc', 'THC'), ('cbd', 'CBD'), ('htcv', 'THCV ')], max_length=1000),
        ),
    ]
