# Generated by Django 4.2.2 on 2024-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_profile_followers'),
        ('cannabis_db', '0003_dispensary_saves_alter_dispensary_shopping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensary',
            name='saves',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_saves', to='memberships.profile'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('Medical_recreational', 'Medical & Recreational'), ('recreational', 'Recreational'), ('medical', 'Medical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('2', '2'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbd', 'CBD'), ('htcv', 'THCV '), ('thc', 'THC'), ('cbg', 'CBG ')], max_length=1000),
        ),
    ]
