# Generated by Django 4.2.2 on 2024-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0004_remove_vendor_ratings_strain_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('1', '1'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.RemoveField(
            model_name='strain',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbg', 'CBG '), ('cbd', 'CBD'), ('thc', 'THC')], max_length=1000),
        ),
        migrations.AddField(
            model_name='strain',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.rating'),
        ),
    ]
