# Generated by Django 4.2.2 on 2024-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0004_dispensary_buy_seeds_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='buy_seeds',
        ),
        migrations.AddField(
            model_name='strain',
            name='seeds',
            field=models.ManyToManyField(related_name='seed_bank_brands', to='cannabis_db.brand'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('2', '2'), ('3', '3'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='accepted_payment_methods',
            field=models.CharField(choices=[('cash_debit_credit', 'Cash, Debit/Credit Cards'), ('cash', 'Cash'), ('debit_credit', 'Debit/Credit Cards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='shopping_options',
            field=models.CharField(blank=True, choices=[('pickup_delivery', 'Pickup/Delivery'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('medical_recreational', 'Medical & Recreational'), ('seed_bank', 'Seed Bank'), ('recreational', 'Recreational')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='effectreport',
            name='type_of_effects',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('neutrial', 'Neutrial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('generic', 'Generic'), ('positive', 'Positive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('2', '2'), ('3', '3'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='title',
            field=models.CharField(blank=True, choices=[('thca', 'THCA '), ('htcv', 'THCV '), ('cbd', 'CBD'), ('thc', 'THC'), ('cbg', 'CBG '), ('cbda', 'CBDA '), ('tac', 'TAC ')], max_length=1000, null=True),
        ),
    ]
