# Generated by Django 4.2.2 on 2024-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_profile_followers'),
        ('cannabis_db', '0004_alter_dispensary_saves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensary',
            name='shopping_options',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('all', 'All'), ('delivery', 'Delivery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('recreational', 'Recreational'), ('medical', 'Medical'), ('Medical_recreational', 'Medical & Recreational')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('generic', 'Generic'), ('positive', 'Positive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('4', '4'), ('2', '2'), ('3', '3'), ('5', '5'), ('1', '1')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='strain_dislikes', to='memberships.profile'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='strain_likes', to='memberships.profile'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbg', 'CBG '), ('thc', 'THC'), ('cbd', 'CBD'), ('htcv', 'THCV ')], max_length=1000),
        ),
    ]
