# Generated by Django 4.2.2 on 2024-01-17 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cannabis_db', '0004_alter_strain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('generic', 'Generic'), ('positive', 'Positive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('sativa', 'Sativa'), ('hybrid', 'Hybrid'), ('indica', 'Indica')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('sativa', 'Sativa'), ('hybrid', 'Hybrid'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('sativa', 'Sativa'), ('hybrid', 'Hybrid'), ('indica', 'Indica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbd', 'CBD'), ('cbg', 'CBG '), ('thc', 'THC'), ('htcv', 'THCV ')], max_length=1000),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('address_id_name', models.CharField(max_length=1000)),
                ('type_of_address', models.CharField(choices=[('billing_address', 'Billing address'), ('shipping_address', 'Shipping address'), ('p_o_box_number', 'Post office box number')], max_length=1000)),
                ('street_name_01', models.CharField(blank=True, max_length=1000, null=True)),
                ('street_name_02', models.CharField(blank=True, max_length=1000, null=True)),
                ('street_city', models.CharField(blank=True, max_length=1000, null=True)),
                ('street_state', localflavor.us.models.USStateField(max_length=2)),
                ('street_zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('default_address', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensary_address',
            field=models.ManyToManyField(to='cannabis_db.address'),
        ),
    ]
