# Generated by Django 4.2.2 on 2024-01-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0006_alter_rating_rating_alter_strain_strain_type_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensary',
            name='dispensary_cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/CANNABIS_DB/DISPENSARY_COVERS/'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='dispensary_logo',
            field=models.ImageField(blank=True, default='media/CANNABIS_DB/DISPENSARY_LOGOS/default_logo.jpg', null=True, upload_to='media/CANNABIS_DB/BRAND_LOGOS/'),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('positive', 'Positive'), ('generic', 'Generic'), ('negative', 'Negative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('4', '4'), ('5', '5'), ('2', '2')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('htcv', 'THCV '), ('thc', 'THC'), ('cbg', 'CBG '), ('cbd', 'CBD')], max_length=1000),
        ),
    ]
