# Generated by Django 4.2.2 on 2024-10-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0008_effectreport_effectreportlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strainspecification',
            name='specification_name',
        ),
        migrations.RemoveField(
            model_name='strainspecificationssets',
            name='specifications_set',
        ),
        migrations.AddField(
            model_name='strainspecification',
            name='title',
            field=models.CharField(blank=True, choices=[('cbd', 'CBD'), ('thc', 'THC'), ('cbda', 'CBDA '), ('thca', 'THCA '), ('cbg', 'CBG '), ('tac', 'TAC '), ('htcv', 'THCV ')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='strainspecificationssets',
            name='specifications',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.strainspecification'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('4', '4'), ('1', '1'), ('3', '3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='shopping_options',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='effectreport',
            name='type_of_effects',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('4', '4'), ('1', '1'), ('3', '3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='StrainSpecifications',
        ),
    ]
