# Generated by Django 4.2.2 on 2024-01-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0008_strain_helps_with_reports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StrainKeywordsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.ManyToManyField(to='cannabis_db.strainkeywords')),
            ],
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('generic', 'Generic'), ('positive', 'Positive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('indica', 'Indica'), ('sativa', 'Sativa'), ('hybrid', 'Hybrid')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('cbd', 'CBD'), ('thc', 'THC'), ('cbg', 'CBG ')], max_length=1000),
        ),
        migrations.CreateModel(
            name='StrainMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_meta_title', models.CharField(max_length=60)),
                ('strain_meta_description', models.TextField(max_length=160)),
                ('strain_meta_keywords', models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.strainkeywordsset')),
            ],
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_metas_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strain_metas', to='cannabis_db.strainmetas'),
        ),
    ]
