# Generated by Django 4.2.2 on 2024-01-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0010_alter_feelingreport_type_of_feelings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensarySocialFollowURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensary_social_profile_name', models.CharField(blank=True, max_length=300, null=True)),
                ('dispensary_social_profile_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('sativa', 'Sativa'), ('indica', 'Indica')], max_length=70),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('thc', 'THC'), ('cbd', 'CBD'), ('cbg', 'CBG ')], max_length=1000),
        ),
        migrations.CreateModel(
            name='DispensarySocialFollowURLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_profiles_URLS', models.ManyToManyField(blank=True, to='cannabis_db.dispensarysocialfollowurl')),
            ],
        ),
        migrations.CreateModel(
            name='DispensarySocialFollows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensary_social_follows_name', models.CharField(blank=True, max_length=300, null=True)),
                ('social_profiles_URLS', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.dispensarysocialfollowurls')),
            ],
        ),
    ]
