# Generated by Django 4.2.2 on 2024-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0010_alter_dispensary_type_of_dispensary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='shopping_options',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('all', 'All'), ('delivery', 'Delivery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('recreational', 'Recreational'), ('medical', 'Medical'), ('Medical_recreational', 'Medical & Recreational')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('1', '1'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_name',
            field=models.CharField(choices=[('htcv', 'THCV '), ('cbg', 'CBG '), ('cbd', 'CBD'), ('thc', 'THC')], max_length=1000),
        ),
    ]
