# Generated by Django 4.2.2 on 2025-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0011_alter_dispensary_accepted_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='cbda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='accepted_payment_methods',
            field=models.CharField(choices=[('debit_credit', 'Debit/Credit Cards'), ('cash_debit_credit', 'Cash, Debit/Credit Cards'), ('cash', 'Cash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='shopping_options',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('pickup_delivery', 'Pickup/Delivery'), ('delivery', 'Delivery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('medical_recreational', 'Medical & Recreational'), ('medical', 'Medical'), ('recreational', 'Recreational'), ('seed_bank', 'Seed Bank')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('indica', 'Indica'), ('sativa', 'Sativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_value_label',
            field=models.CharField(blank=True, choices=[('percentage', '%'), ('mg', 'mg')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='title',
            field=models.CharField(blank=True, choices=[('thca', 'THCA '), ('cbda', 'CBDA '), ('cbg', 'CBG '), ('htcv', 'THCV '), ('thc', 'THC'), ('cbd', 'CBD'), ('tac', 'TAC ')], max_length=1000, null=True),
        ),
    ]
