# Generated by Django 4.2.2 on 2024-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0017_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerpeneIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terpene_icon', models.ImageField(blank=True, default='media/CANNABIS_DB/STRAINS/TERPENES_REPORTS/TERPENE_ICONS/default.jpg/', max_length=500, null=True, upload_to='media/CANNABIS_DB/STRAINS/TERPENES_REPORTS/TERPENE_ICONS/')),
            ],
        ),
        migrations.CreateModel(
            name='TerpeneValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terpene_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='terpenedetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='terpenedetails',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='terpenedetails',
            name='terpene_value',
        ),
        migrations.RemoveField(
            model_name='terpenedetails',
            name='title',
        ),
        migrations.AddField(
            model_name='terpenedetails',
            name='terpene',
            field=models.CharField(choices=[('', '')], default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('5', '5'), ('4', '4'), ('3', '3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='accepted_payment_methods',
            field=models.CharField(choices=[('cash', 'Cash'), ('cash_debit_credit', 'Cash, Debit/Credit Cards'), ('debit_credit', 'Debit/Credit Cards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='shopping_options',
            field=models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('pickup_delivery', 'Pickup/Delivery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('medical_recreational', 'Medical & Recreational'), ('recreational', 'Recreational'), ('seed_bank', 'Seed Bank')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='effectreport',
            name='type_of_effects',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutrial', 'Neutrial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feelingreport',
            name='type_of_feelings',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('5', '5'), ('4', '4'), ('3', '3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='strain_type_label',
            field=models.CharField(blank=True, choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_01',
            field=models.CharField(blank=True, choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainlineagedetailslistitem',
            name='strain_lineage_02',
            field=models.CharField(blank=True, choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='specification_value_label',
            field=models.CharField(blank=True, choices=[('percentage', '%'), ('mg', 'mg')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='title',
            field=models.CharField(blank=True, choices=[('cbda', 'CBDA '), ('cbg', 'CBG '), ('cbd', 'CBD'), ('thc', 'THC'), ('tac', 'TAC '), ('htcv', 'THCV '), ('thca', 'THCA ')], max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='terpenedetails',
            name='terpene_icon',
        ),
        migrations.AddField(
            model_name='terpenedetails',
            name='terpene_values',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.terpenevalue'),
        ),
        migrations.AddField(
            model_name='terpenedetails',
            name='terpene_icon',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.terpeneicon'),
        ),
    ]
