# Generated by Django 4.2.2 on 2024-10-31 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cannabis_db', '0020_helpswithreportlistset_hw_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aromaslistset',
            old_name='aromas_list_set_name',
            new_name='als_UNIQUE_ID',
        ),
        migrations.AddField(
            model_name='strain',
            name='feelings',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.feelingreport'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('5', '5'), ('3', '3'), ('4', '4'), ('2', '2'), ('1', '1')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='dispensary_address',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.address'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='dispensary_followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispensary_followers', to='memberships.profile'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='tagline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='type_of_dispensary',
            field=models.CharField(blank=True, choices=[('Medical_recreational', 'Medical & Recreational'), ('recreational', 'Recreational'), ('medical', 'Medical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='effectreport',
            name='type_of_effects',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('neutrial', 'Neutrial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('5', '5'), ('3', '3'), ('4', '4'), ('2', '2'), ('1', '1')], max_length=5),
        ),
        migrations.AlterField(
            model_name='strainspecification',
            name='title',
            field=models.CharField(blank=True, choices=[('cbda', 'CBDA '), ('tac', 'TAC '), ('htcv', 'THCV '), ('cbd', 'CBD'), ('thc', 'THC'), ('thca', 'THCA '), ('cbg', 'CBG ')], max_length=1000, null=True),
        ),
    ]
