# Generated by Django 4.2.2 on 2024-11-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_lega_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='d_b_a',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_address_line_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_address_line_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_unit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='legal_business_zip_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tax_ID',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='type_of_business',
        ),
    ]
