# Generated by Django 4.2.2 on 2025-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0012_strain_cbda_and_more'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consumed_strains',
            field=models.ManyToManyField(blank=True, null=True, related_name='consumed_strains', to='cannabis_db.strain'),
        ),
    ]
