# Generated by Django 4.2.2 on 2024-01-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0002_alter_feelingreport_type_of_feelings_and_more'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_strains',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.strain'),
        ),
    ]
