# Generated by Django 4.2.2 on 2024-11-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0028_alter_comment_rating_and_more'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarked_strains', to='cannabis_db.strain'),
        ),
    ]
