# Generated by Django 4.2.2 on 2024-11-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0035_alter_comment_rating_and_more'),
        ('memberships', '0004_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cannabis_db.address'),
            preserve_default=False,
        ),
    ]
