# Generated by Django 4.2.2 on 2024-11-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visibility_options',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50, null=True),
        ),
    ]
