# Generated by Django 4.2.18 on 2025-02-24 11:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariationSet',
            new_name='ProductVariationsSet',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pricing',
            new_name='pricing_management',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_SKU',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_pricing_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.pricingmanagement'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_product_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productgalleryimagesset'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_stock_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.stockmanagement'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_thumbnail',
            field=models.ImageField(default='', upload_to='media/DJANGO_ECOMMERCE/PRODUCTS/VARIATIONS/VARIATIONS_THUMBNAILS/'),
        ),
    ]
