# Generated by Django 4.2.2 on 2025-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis_db', '0005_alter_dispensary_accepted_payment_methods_and_more'),
        ('catalog', '0002_alter_product_brands_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dispensaries',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis_db.dispensary'),
        ),
    ]
