# Generated by Django 4.2.2 on 2025-05-06 09:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0002_alter_address_address_type_and_more'),
        ('cannabis_db', '0008_alter_dispensary_accepted_payment_methods_and_more'),
        ('memberships', '0001_initial'),
        ('catalog', '0003_product_dispensaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSocialFollowURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_social_profile_name', models.CharField(blank=True, max_length=300, null=True)),
                ('brand_social_profile_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandSocialFollowURLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_profiles_URLS', models.ManyToManyField(blank=True, to='catalog.brandsocialfollowurl')),
            ],
        ),
        migrations.CreateModel(
            name='BrandSocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_social_follows_name', models.CharField(blank=True, max_length=300, null=True)),
                ('social_profiles_URLS', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.brandsocialfollowurls')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(max_length=1000)),
                ('tagline', models.CharField(blank=True, max_length=1000, null=True)),
                ('websiteURL', models.URLField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=300, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='media/CANNABIS_DB/BRAND_LOGOS/')),
                ('brand_cover', models.ImageField(blank=True, null=True, upload_to='media/CANNABIS_DB/BRAND_COVERS/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('claimed', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('author', models.ManyToManyField(blank=True, null=True, related_name='brand_author', to=settings.AUTH_USER_MODEL)),
                ('brand_address', models.ManyToManyField(blank=True, null=True, related_name='brand_address', to='addresses.address')),
                ('brand_followers', models.ManyToManyField(blank=True, null=True, related_name='brand_followers', to='memberships.profile')),
                ('brand_metas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_meta_set', to='cannabis_db.metasset')),
                ('brand_products', models.ManyToManyField(blank=True, null=True, related_name='brandd_products', to='catalog.product')),
                ('brand_social_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.brandsocialprofile')),
                ('brand_strains', models.ManyToManyField(blank=True, null=True, related_name='brandd_strains', to='cannabis_db.strain')),
                ('dispensary', models.ManyToManyField(blank=True, null=True, related_name='brand_dispensary', to='cannabis_db.dispensary')),
            ],
        ),
    ]
