# Generated by Django 4.2.18 on 2025-02-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariation_variation_attributes_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributesset',
            old_name='pgis_UNIQUE_ID',
            new_name='as_UNIQUE_ID',
        ),
    ]
