# Generated by Django 4.2.2 on 2025-05-06 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cannabis_db', '0009_alter_dispensary_shopping_options_and_more'),
        ('addresses', '0002_alter_address_address_type_and_more'),
        ('catalog', '0004_brandsocialfollowurl_brandsocialfollowurls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalog_brand_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_address',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalog_brand_address', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalog_brand_followers', to='memberships.profile'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalog_brand_products', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_strains',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalog_brand_strains', to='cannabis_db.strain'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='dispensary',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalog_brand_dispensary', to='cannabis_db.dispensary'),
        ),
    ]
