# Generated by Django 4.2.18 on 2025-02-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_pgis_unique_id_attributesset_as_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariationsset',
            name='pvs_UNIQUE_ID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariationsset',
            name='variations',
            field=models.ManyToManyField(to='catalog.productvariation'),
        ),
    ]
