# Generated by Django 4.2.18 on 2025-02-24 23:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariationsset_pvs_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='variation_description',
            new_name='variation_full_description',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_description_list_set',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.descriptionlist'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True),
        ),
    ]
