# Generated by Django 4.2.18 on 2025-02-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_variation_description_productvariation_variation_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_visibility',
            field=models.CharField(blank=True, choices=[('single_product', 'Single product'), ('variable_product', 'Variable product'), ('digital_product', 'Digital product'), ('dropship_product', 'Dropship product')], max_length=255, null=True),
        ),
    ]
