# Generated by Django 4.2.18 on 2025-02-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_product_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_visibility',
            field=models.CharField(blank=True, choices=[('hidden', 'Hidden'), ('private', 'Private'), ('visible', 'Visible')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TagsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_UINIQUE_ID', models.CharField(max_length=50)),
                ('tags', models.ManyToManyField(to='catalog.tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tagsset'),
        ),
    ]
