# Generated by Django 4.2.18 on 2025-02-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_tag_alter_product_product_visibility_tagsset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.ManyToManyField(to='catalog.keywords')),
            ],
        ),
        migrations.CreateModel(
            name='MetasSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_UNIQUE_ID', models.CharField(max_length=160)),
                ('strain_meta_description', models.TextField(blank=True, max_length=160, null=True)),
                ('strain_meta_keywords', models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.keywordsset')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_metas_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strain_metas', to='catalog.metasset'),
        ),
    ]
