# Generated by Django 4.2.18 on 2025-02-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_keywords_keywordsset_metasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_UNIQUE_ID', models.CharField(max_length=50)),
                ('weight_label', models.CharField(blank=True, choices=[('gm', 'Gm'), ('kg', 'Kg'), ('ounce', 'OZ'), ('lbs', 'Lb')], max_length=50, null=True)),
                ('dimension_length', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dimension_width', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dimension_height', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.shippingsettings'),
        ),
    ]
