# Generated by Django 4.2.18 on 2025-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_shippingsettings_product_shipping_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionlistitem',
            old_name='description_list_items',
            new_name='description_list_item',
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='weight_label',
            field=models.CharField(blank=True, choices=[('gm', 'Gm'), ('kg', 'Kg'), ('ounce', 'Oz'), ('lbs', 'Lb')], max_length=50, null=True),
        ),
    ]
