# Generated by Django 4.2.18 on 2025-02-26 16:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_brand_date_created_brand_date_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionlistitem',
            name='description_list_item',
        ),
        migrations.AddField(
            model_name='descriptionlistitem',
            name='description_list_item_image',
            field=models.ImageField(default='', upload_to='media/DJANGO_ECOMMERCE/PRODUCTS/DESCRIPTION_LIST_ITEMS_IMAGES/'),
        ),
        migrations.AddField(
            model_name='descriptionlistitem',
            name='description_list_item_short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='descriptionlistitem',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptionlistitem',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
