# Generated by Django 4.2.18 on 2025-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_descriptionlistitem_description_list_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(blank=True, choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('active', 'Active')], max_length=255, null=True),
        ),
    ]
