# Generated by Django 4.2.18 on 2025-02-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgalleryimages',
            old_name='images',
            new_name='gallery_images',
        ),
        migrations.RenameField(
            model_name='productgalleryimagesset',
            old_name='images',
            new_name='gallery_images_set',
        ),
    ]
