# Generated by Django 4.2.18 on 2025-02-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_rename_images_productgalleryimages_gallery_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanagement',
            name='sm_UNIQUE_ID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
