# Generated by Django 4.2.18 on 2025-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_stockmanagement_sm_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmanagement',
            name='p_UNIQUE_ID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
