# Generated by Django 4.2.18 on 2025-02-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_pricingmanagement_p_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metasset',
            old_name='sms_UNIQUE_ID',
            new_name='ms_UNIQUE_ID',
        ),
    ]
