# Generated by Django 4.2.2 on 2025-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_dispensaries'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.category'),
        ),
    ]
